name: lint
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  awesome-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npx awesome-lint
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: markdown-lint
        uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          globs: |
            **/*.md
